export const ON_CHANGE_NAME = 'ON_CHANGE_NAME';
export const ON_CHANGE_DESCRIPTION = 'ON_CHANGE_DESCRIPTION';
export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY';
export const ON_CHANGE_LOCATION = 'ON_CHANGE_LOCATION';
export const ON_CHANGE_DATE = 'ON_CHANGE_DATE';
export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';
