export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SHOW_CREATE_EVENT_MODAL = 'SHOW_CREATE_EVENT_MODAL';
export const EVENT_UPDATED = 'EVENT_UPDATED';
